# Continuous Integration Workflow
#
# Runs on pull requests and pushes to main branch
# - Lints code
# - Type checks
# - Runs tests with coverage
# - Builds application

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'ai-survey-app/package-lock.json'

      - name: Install dependencies
        working-directory: ./ai-survey-app
        run: npm ci --legacy-peer-deps

      - name: Run ESLint
        working-directory: ./ai-survey-app
        run: npm run lint

      - name: Run TypeScript type check
        working-directory: ./ai-survey-app
        run: npm run type-check

      - name: Run tests with coverage
        working-directory: ./ai-survey-app
        run: npm run test:ci
        env:
          NODE_ENV: test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./ai-survey-app/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'ai-survey-app/package-lock.json'

      - name: Install dependencies
        working-directory: ./ai-survey-app
        run: npm ci --legacy-peer-deps

      - name: Build application
        working-directory: ./ai-survey-app
        run: npm run build
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_SECRET: test-secret-for-build
          NEXTAUTH_URL: http://localhost:3000

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ai-survey-app/.next
          retention-days: 7
